/*
    M:N 관계
    1. 현실세계에서 빈번히 나타나지만 주의해야 하는 관계이다.
    2. M:N 관계를 가진 2개의 테이블은 직접 관계를 맺는 것이 불가능하다.
    3. 관계를 맺기 위한 별도의 테이블이 추가로 필요하다.
    4. M:N 관계는 1:M 관계 2개로 구현할 수 있다.
*/

--삭제는 생성의 역순
DROP TABLE ENROLL_T;
DROP TABLE SUBJECT_T;
DROP TABLE STUDENT_T;

--학생 테이블
CREATE TABLE STUDENT_T(
    STU_NO   NUMBER       NOT NULL PRIMARY KEY,
    STU_NAME VARCHAR2(16) NOT NULL,
    STU_AGE  NUMBER       NOT NULL
);

--과목 테이블
CREATE TABLE SUBJECT_T(
    SUJ_CODE  VARCHAR2(5)  NOT NULL PRIMARY KEY,
    SUJ_NAME  VARCHAR2(10) NOT NULL,
    PROFESSOR VARCHAR2(10) NOT NULL
);

--수강신청 테이블
CREATE TABLE ENROLL_T(
    ENROLL_NO NUMBER      NOT NULL PRIMARY KEY,
    STU_NO    NUMBER      NOT NULL REFERENCES STUDENT_T(STU_NO),
    SUJ_CODE  VARCHAR2(5) NOT NULL REFERENCES SUBJECT_T(SUJ_CODE)
);