-- 1. LOCATION_ID가 1700인 부서에 근무하는 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME을 조회하시오.
-- 1) ANSI
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , DEPARTMENT_NAME
     , LOCATION_ID
  FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.LOCATION_ID = 1700;


-- 2) 오라클
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , DEPARTMENT_NAME
     , LOCATION_ID
  FROM DEPARTMENTS D, EMPLOYEES E
 WHERE D.LOCATION_ID = 1700;

-- 2. DEPARTMENT_NAME이 'Executive'인 부서에 근무하는 사원들의 EMPLOYEE_ID, FIRST_NAME을 조회하시오.
-- 1) ANSI
SELECT EMPLOYEE_ID
     , FIRST_NAME
  FROM DEPARTMENTS D INNER JOIN EMPLOYEES
    ON DEPARTMENT_NAME = 'Executive';


-- 2) 오라클
SELECT EMPLOYEE_ID
     , FIRST_NAME
  FROM DEPARTMENTS D, EMPLOYEES
 WHERE DEPARTMENT_NAME = 'Executive';


-- 3. 모든 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, STREET_ADDRESS, CITY를 조회하시오.
-- 1) ANSI
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , DEPARTMENT_NAME
     , STREET_ADDRESS
     , CITY
  FROM LOCATIONS L INNER JOIN DEPARTMENTS D
    ON L.LOCATION_ID = D.LOCATION_ID INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;
-- 2) 오라클
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , DEPARTMENT_NAME
     , STREET_ADDRESS
     , CITY
  FROM LOCATIONS L, DEPARTMENTS D, EMPLOYEES E
 WHERE L.LOCATION_ID = D.LOCATION_ID
   AND D.DEPARTMENT_ID = E.DEPARTMENT_ID;


-- 4. 부서별 DEPARTMENT_NAME과 사원 수와 평균 연봉을 조회하시오.
-- 1) ANSI
SELECT DISTINCT D.DEPARTMENT_NAME                               AS 부서이름
     , COUNT(*) OVER(PARTITION BY E.DEPARTMENT_ID)              AS 사원수
     , TRUNC(AVG(SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME))  AS 평균연봉
  FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;


-- 2) 오라클
SELECT DISTINCT D.DEPARTMENT_NAME                               AS 부서이름
     , COUNT(*) OVER(PARTITION BY E.DEPARTMENT_ID)              AS 사원수
     , TRUNC(AVG(SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME))  AS 평균연봉
  FROM DEPARTMENTS D, EMPLOYEES E
 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID;


-- 5. 모든 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME을 조회하시오. 부서가 없는 사원의 부서명은 'None'으로 조회되도록 처리하시오.
-- 1) ANSI
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , NVL(DEPARTMENT_NAME,'None')
  FROM DEPARTMENTS D RIGHT OUTER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 ORDER BY EMPLOYEE_ID;


-- 2) 오라클
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , NVL(DEPARTMENT_NAME,'None')
  FROM DEPARTMENTS D, EMPLOYEES E
 WHERE D.DEPARTMENT_ID(+) = E.DEPARTMENT_ID
 ORDER BY EMPLOYEE_ID;


-- 6. 모든 부서의 DEPARTMENT_NAME과 근무 중인 사원 수를 조회하시오. 근무하는 사원이 없으면 0으로 조회하시오.
-- 1) ANSI
SELECT DISTINCT D.DEPARTMENT_ID                                     AS 부서ID
     , DEPARTMENT_NAME                                              AS 부서이름
     , COUNT(E.DEPARTMENT_ID) OVER(PARTITION BY E.DEPARTMENT_ID)    AS 사원수
  FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 ORDER BY D.DEPARTMENT_ID;


SELECT COUNT(*)
     , DEPARTMENT_ID
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;
 
-- 2) 오라클
SELECT DISTINCT D.DEPARTMENT_ID                                     AS 부서ID
     , DEPARTMENT_NAME                                              AS 부서이름
     , COUNT(E.DEPARTMENT_ID) OVER(PARTITION BY E.DEPARTMENT_ID)    AS 사원수
  FROM DEPARTMENTS D, EMPLOYEES E
 WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID(+)
 ORDER BY D.DEPARTMENT_ID;


-- 7. 모든 부서의 DEPARTMENT_ID, DEPARTMENT_NAME, STATE_PROVINCE, COUNTRY_NAME, REGION_NAME을 조회하시오.
-- 1) ANSI
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
     , COUNTRY_NAME
     , STATE_PROVINCE
     , REGION_NAME
  FROM REGIONS R INNER JOIN COUNTRIES C
    ON R.REGION_ID = C.REGION_ID INNER JOIN LOCATIONS L
    ON C.COUNTRY_ID = L.COUNTRY_ID INNER JOIN DEPARTMENTS D
    ON L.LOCATION_ID = D.LOCATION_ID
 ORDER BY D.DEPARTMENT_ID;

-- 2) 오라클
SELECT DEPARTMENT_ID
     , DEPARTMENT_NAME
     , COUNTRY_NAME
     , STATE_PROVINCE
     , REGION_NAME
  FROM REGIONS R, COUNTRIES C, LOCATIONS L, DEPARTMENTS D
 WHERE R.REGION_ID = C.REGION_ID 
   AND C.COUNTRY_ID = L.COUNTRY_ID
   AND L.LOCATION_ID = D.LOCATION_ID
 ORDER BY D.DEPARTMENT_ID;


-- 8. 모든 사원들의 EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER의 FIRST_NAME을 조회하시오. (SELF JOIN)
-- 1) ANSI


-- 2) 오라클



-- 9. 각 사원 중에서 매니저보다 먼저 입사한 사원을 조회하시오. (SELF JOIN)
-- 1) ANSI


-- 2) 오라클



-- 10. 같은 부서에 근무하는 사원 중에서 나보다 SALARY가 높은 사원 정보를 조회하시오. (SELF JOIN)
-- 1) ANSI

-- 2) 오라클