--테이블 삭제
DROP TABLE EMPLOYEE_T;
DROP TABLE DEPARTMENT_T;

--부서 테이블 생성
CREATE TABLE DEPARTMENT_T(
    DEPT_NO   NUMBER,
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCATION  VARCHAR2(15) NOT NULL
);

--사원 테이블 생성
CREATE TABLE EMPLOYEE_T(
    EMP_NO    NUMBER,
    NAME      VARCHAR2(20) NOT NULL,
    DEPART    NUMBER,
    POSITION  VARCHAR2(20),
    GENDER    CHAR(2),
    HIRE_DATE DATE,
    SALARY    NUMBER
);

--기본키 설정
ALTER TABLE DEPARTMENT_T ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
ALTER TABLE EMPLOYEE_T   ADD CONSTRAINT PK_EMPLOYEE   PRIMARY KEY(EMP_NO);

--외래키 설정
ALTER TABLE EMPLOYEE_T ADD CONSTRAINT FK_DEPARTMENT_EMPLOYEE FOREIGN KEY(DEPART) REFERENCES DEPARTMENT_T(DEPT_NO);

--부서번호를 생성하는 시퀀스 만들기
/*
CREATE SEQUENCE DEPT_SEQ
    INCREMENT BY 1     -- 1씩 증가하는 번호를 만든다.(디폴트)
    START WITH 1       -- 1부터 번호를 만든다.(디폴트)
    NOMAXVALUE         -- 번호의 상한선이 없다.(디폴트)
    NOMINVALUE         -- 번호의 하한선이 없다.(디폴트)
    NOCYCLE            -- 번호순환이 없다.(디폴트)
    CACHE 20           -- 20개씩 번호를 미리 만들어 둔다.(디폴트)
    NOORDER            -- 번호를 순서대로 사용하지 않는다.(디폴트) - 번호를 순서대로 사용하는 ORDER 옵션으로 바꿔서 시퀀스를 생성한다.
;
*/

DROP SEQUENCE DEPT_SEQ;
CREATE SEQUENCE DEPT_SEQ ORDER;

INSERT INTO DEPARTMENT_T(DEPT_NO,DEPT_NAME,LOCATION) VALUES(DEPT_SEQ.NEXTVAL, '영업부', '대구');
INSERT INTO DEPARTMENT_T(DEPT_NO,DEPT_NAME,LOCATION) VALUES(DEPT_SEQ.NEXTVAL, '인사부', '서울');
INSERT INTO DEPARTMENT_T(DEPT_NO,DEPT_NAME,LOCATION) VALUES(DEPT_SEQ.NEXTVAL, '총무부', '대구');
INSERT INTO DEPARTMENT_T(DEPT_NO,DEPT_NAME,LOCATION) VALUES(DEPT_SEQ.NEXTVAL, '기획부', '서울');

SELECT * FROM DEPARTMENT_T; 
