--테이블 삭제
DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;

--국가 테이블 생성
CREATE TABLE NATION_TBL(
    N_CODE         NUMBER(3)    NOT NULL,
    N_NAME         VARCHAR2(30) NOT NULL,
    N_PARTI_PERSON NUMBER       DEFAULT 0,
    N_PARTI_EVENT  NUMBER,
    N_PREV_RANK    NUMBER,
    N_CURR_RANK    NUMBER
);

--종목 테이블 생성
CREATE TABLE EVENT_TBL(
    E_CODE       NUMBER       NOT NULL,
    E_NAME       VARCHAR2(30) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO       VARCHAR2(100)
);

--선수 테이블 생성
CREATE TABLE PLAYER_TBL(
    P_CODE NUMBER(3)    NOT NULL,
    P_NAME VARCHAR2(30) NOT NULL,
    N_CODE NUMBER(3)    NOT NULL,
    E_CODE NUMBER       NOT NULL,
    P_RANK NUMBER,
    P_AGE  NUMBER(3)
);

--일정 테이블 생성
CREATE TABLE SCHEDULE_TBL(
    S_NO         NUMBER(3)      NOT NULL,
    N_CODE       NUMBER(3),
    E_CODE       NUMBER,
    S_START_DATE DATE,
    S_END_DATE   DATE,
    S_INFO       VARCHAR2(100)
);

--기본키 설정
ALTER TABLE NATION_TBL   ADD CONSTRAINT PK_NATION   PRIMARY KEY(N_CODE);
ALTER TABLE EVENT_TBL    ADD CONSTRAINT PK_EVENT    PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER_TBL   ADD CONSTRAINT PK_PLAYER   PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY(S_NO);

--선수 테이블 외래키 설정
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_NATION_PLAYER FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE CASCADE;
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_EVENT_PLAYER  FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE)  ON DELETE CASCADE;

--일정 테이블 외래키 설정
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_NATION_SCHEDULE FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE SET NULL;
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_EVENT_SCHEDULE  FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE)  ON DELETE SET NULL;
            


--국가 테이블의 기본키 삭제하기
--국가 테이블의 깁노키를 참조하는 외래키를 먼저 삭제해야 한다.
ALTER TABLE PLAYER_TBL   DROP CONSTRAINT FK_NATION_PLAYER;
ALTER TABLE SCHEDULE_TBL DROP CONSTRAINT FK_NATION_SCHEDULE;
ALTER TABLE NATION_TBL   DROP CONSTRAINT PK_NATION;   --외래키가 참조하고 있을 경우에 지워지지 않는다.


--선수 테이블의 FK_EVENT_PLAYER 외래키 일시중지하기
ALTER TABLE PLAYER_TBL DISABLE CONSTRAINT FK_EVENT_PLAYER;

--선수 테이블의 FK_EVENT_PLAYER 외래키 다시시작하기
ALTER TABLE PLAYER_TBL ENABLE CONSTRAINT FK_EVENT_PLAYER;